[project]
name = "ai-pr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "setuptools>=80.10.2",
    "rich>=13.0.0",
]

[project.scripts]
ai-pr="ai_pr.cli:main"
